version: "3"

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres"
    restart: always
    volumes: 
      - banco-de-dados:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes: 
  banco-de-dados:
